minimumReleaseAge: 10080 # 7 days

minimumReleaseAgeExclude:
  - '@typescript-eslint/eslint-plugin'
  - '@typescript-eslint/parser'
  - '@typescript-eslint/project-service'
  - '@typescript-eslint/scope-manager'
  - '@typescript-eslint/tsconfig-utils'
  - '@typescript-eslint/type-utils'
  - '@typescript-eslint/types'
  - '@typescript-eslint/typescript-estree'
  - '@typescript-eslint/utils'
  - '@typescript-eslint/visitor-keys'
  - typescript-eslint

onlyBuiltDependencies:
  - esbuild
  - msw

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # 30 days
